# numpy

## array introduction

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,4,6,8])

In [3]:
myarr

array([3, 4, 6, 8])

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(4,)

In [6]:
myarr=np.array([3,4,6,8],np.int32)

In [7]:
myarr

array([3, 4, 6, 8], dtype=int32)

In [8]:
myarr=np.array([[3,4,6,8]])
#makimg 2 dimension array

In [9]:
myarr[0,1]
#zeroth raw and 1 coloumn

4

In [10]:
myarr[0,2]=56
#replace elements with 56 number

In [11]:
myarr

array([[ 3,  4, 56,  8]])

## array methods

***1)convertion from other python structure***

In [12]:
listarray=np.array([[1,2,3],[5,6,7],[2,4,5]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [2, 4, 5]])

In [14]:
listarray.dtype

dtype('int64')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({5,6,7,8})
#here dtype is object
#make sure for high efficiency
#array is float and integer

array({8, 5, 6, 7}, dtype=object)

***2)intrinsic array(arange,ones,zerosetc)***

In [18]:
zeros=np.zeros((2,4))

In [19]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
lspace=np.linspace(1,5,6)
#equally distribt value 1 to 5 in 6 number

In [22]:
lspace

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [23]:
emt=np.empty((2,2))
#random elements of size 2,2

In [24]:
emt

array([[2.44029516e-312, 2.05833592e-312],
       [2.14321575e-312, 0.00000000e+000]])

In [25]:
emt_like=np.empty_like(lspace)
#random array of size lspace array

In [26]:
emt_like

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [27]:
ide=np.identity(2)
#creating identity array

In [28]:
ide

array([[1., 0.],
       [0., 1.]])

In [29]:
ide.shape

(2, 2)

In [30]:
arr=np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr=arr.reshape(2,5)

In [33]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
arr=arr.ravel()
#creating 1 dimension array

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr.shape

(10,)

## numpy axis

In [37]:
x=[[1,2,3],[3,5,6],[2,5,8]]

In [38]:
ar=np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [3, 5, 6],
       [2, 5, 8]])

In [40]:
ar.sum(axis=0)
#sum of element in first row

array([ 6, 12, 17])

In [41]:
ar.sum(axis=1)
#sum of element in first coloumn

array([ 6, 14, 15])

## numpy attributes

In [42]:
ar.T
#transform row into coloumn

array([[1, 3, 2],
       [2, 5, 5],
       [3, 6, 8]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)
#flat is used to print sequence of number
#in ar

1
2
3
3
5
6
2
5
8


In [45]:
ar.ndim
#printing dimension of array

2

In [46]:
ar.size
#size of array

9

In [47]:
ar.nbytes
#printing a bytes taken by array

72

In [48]:
one=np.array([2,3,6,5])

In [49]:
one.argmax()
#given a number were min element is allocated

2

In [50]:
one.argmin()
#given a number were max elements is allocated

0

In [51]:
one.argsort()
#sorting a element number 
#min element on a zero is 2

array([0, 1, 3, 2])

In [52]:
ar

array([[1, 2, 3],
       [3, 5, 6],
       [2, 5, 8]])

In [53]:
ar.argmin()

0

In [54]:
ar.argmax()

8

In [55]:
ar.argmax(axis=0)

array([1, 1, 2])

In [56]:
ar.argmax(axis=1)

array([2, 2, 2])

In [57]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [58]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [2, 1, 1],
       [1, 2, 2]])

In [59]:
ar.ravel()

array([1, 2, 3, 3, 5, 6, 2, 5, 8])

## mathematics operation

In [60]:
ar1=np.array([[2,4,5],[5,3,2],[3,6,7]])

In [61]:
ar2=np.array([[2,4,5],[5,3,2],[3,6,7]])

In [62]:
ar1+ar2

array([[ 4,  8, 10],
       [10,  6,  4],
       [ 6, 12, 14]])

In [63]:
ar1*ar2

array([[ 4, 16, 25],
       [25,  9,  4],
       [ 9, 36, 49]])

In [64]:
np.sqrt(ar1)

array([[1.41421356, 2.        , 2.23606798],
       [2.23606798, 1.73205081, 1.41421356],
       [1.73205081, 2.44948974, 2.64575131]])

In [65]:
ar.sum()

35

In [66]:
ar1

array([[2, 4, 5],
       [5, 3, 2],
       [3, 6, 7]])

In [67]:
np.where(ar1>5)
#that means 2 row and second coloumn 
#element is greater that 5

(array([2, 2]), array([1, 2]))

In [68]:
np.count_nonzero(ar1)
#non zero element counting

9

In [69]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

## numpy array faster than python list

In [70]:
import sys

In [71]:
py_ar=[5,6,7,8]#python list

In [72]:
np_ar=np.array(py_ar)#numpy array

In [73]:
sys.getsizeof(1)*len(py_ar)
#one item size×total item

112

In [74]:
np_ar.itemsize*np_ar.size
#one item size×total item

32